name: Fetch tournament data
on:
  schedule:
    - cron: 0 * * * *

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: bash update_active.sh active.csv
      # Do I need to do git adds here?